name: Publish release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish and Zip Release
        run: |
          cd ./scripts
          chmod +x ./publish.sh
          ./publish.sh --runtime linux-x64

      - name: Read Version
        id: version
        run: echo "version=$(cat ./src/Ray.BiliBiliTool.Console/bin/Publish/version.txt)" >> $GITHUB_OUTPUT

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: './src/Ray.BiliBiliTool.Console/bin/Publish/*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.version.outputs.version }}
